# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "507902cde9b8d091cd34143c9e3bf901"
name = "order-notes"
handle = "order-notes-5"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "shiv-dev-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
